services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
      - EMAIL_SENDER_ADDRESS=${EMAIL_SENDER_ADDRESS}
    env_file:
      - .env.dev
    restart: unless-stopped
    networks:
      - inflow-network

networks:
  inflow-network:
    driver: bridge
